// Under Progress extension — keeps display settings, saved presets, and disability profile metadata in browser storage.
const root = document.documentElement;
let savedProfile = null;

function normalizedSettings(state = {}) { return { textScale: Number(state.textScale ?? 100), lineSpacing: Number(state.lineSpacing ?? 1.5), readingWidth: Number(state.readingWidth ?? 70), contrast: Boolean(state.contrast), focus: Boolean(state.focus) }; }
function apply(state) { const next = normalizedSettings(state); root.style.setProperty("--up-text-scale", `${next.textScale / 100}`); root.style.setProperty("--up-line-spacing", String(next.lineSpacing)); root.style.setProperty("--up-reading-width", `${next.readingWidth}ch`); root.dataset.upContrast = String(next.contrast); root.dataset.upFocus = String(next.focus); }
function isUnderProgressWebsite() { const host = window.location.hostname; return host === "under-progress-psi.vercel.app" || /^under-progress(?:-[a-z0-9-]+)?\.vercel\.app$/.test(host); }
function sendProfileToWebsite(settings) { if (!isUnderProgressWebsite() || !settings) return; window.postMessage({ source: "under-progress-extension", type: "extension-profile", settings: normalizedSettings(settings), profile: savedProfile }, window.location.origin); }

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { if (!message) return; if (message.type === "ping") { sendResponse?.({ ready: true }); return; } if (message.type === "apply") { apply(message.state); sendResponse?.({ applied: true }); return; } if (message.type === "speak") { const selected = window.getSelection()?.toString().trim(); const fallback = document.querySelector("main, article, [role=main]")?.innerText?.slice(0, 1800) || document.body.innerText.slice(0, 1800); const text = selected || fallback; if (text) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); window.speechSynthesis.speak(utterance); } sendResponse?.({ applied: Boolean(text), error: text ? undefined : "No readable text was found." }); return; } if (message.type === "pause-speech") { if (window.speechSynthesis.speaking && !window.speechSynthesis.paused) { window.speechSynthesis.pause(); sendResponse?.({ applied: true }); } else sendResponse?.({ applied: false, error: "There is no active reading to pause." }); return; } if (message.type === "resume-speech") { if (window.speechSynthesis.paused) { window.speechSynthesis.resume(); sendResponse?.({ applied: true }); } else sendResponse?.({ applied: false, error: "There is no paused reading to resume." }); } });
chrome.storage.sync.get(["underProgress", "underProgressProfile"], ({ underProgress, underProgressProfile }) => { savedProfile = underProgressProfile || null; if (underProgress && !isUnderProgressWebsite()) apply(underProgress); if (isUnderProgressWebsite()) { window.postMessage({ source: "under-progress-extension", type: "connection-status" }, window.location.origin); sendProfileToWebsite(underProgress); } });
chrome.storage.onChanged.addListener((changes, areaName) => { if (areaName !== "sync") return; if (changes.underProgressProfile) savedProfile = changes.underProgressProfile.newValue || null; if (changes.underProgress) { const settings = normalizedSettings(changes.underProgress.newValue); if (!isUnderProgressWebsite()) apply(settings); sendProfileToWebsite(settings); } });
window.addEventListener("message", (event) => { if (!isUnderProgressWebsite() || event.origin !== window.location.origin || event.source !== window) return; const message = event.data; if (!message || message.source !== "under-progress-website") return; if (message.type === "request-profile") { chrome.storage.sync.get(["underProgress", "underProgressProfile"], ({ underProgress, underProgressProfile }) => { savedProfile = underProgressProfile || null; window.postMessage({ source: "under-progress-extension", type: "connection-status" }, window.location.origin); sendProfileToWebsite(underProgress); }); } if (message.type === "save-profile" && message.settings) { const settings = normalizedSettings(message.settings); savedProfile = message.profile || savedProfile; const preset = { id: "website-default", name: savedProfile?.presetName || "Website default", settings }; chrome.storage.sync.get(["underProgressPresets"], ({ underProgressPresets }) => { const previous = Array.isArray(underProgressPresets) ? underProgressPresets.filter(item => item?.id !== "website-default") : []; chrome.storage.sync.set({ underProgress: settings, underProgressProfile: savedProfile, underProgressPresets: [...previous, preset], underProgressDefaultPreset: "website-default" }, () => { window.postMessage({ source: "under-progress-extension", type: "preset-saved", presetName: preset.name }, window.location.origin); }); }); } });
