// Under Progress extension — keeps display settings, saved presets, and disability profile metadata in browser storage.
const root = document.documentElement;
let savedProfile = null;
let preferredSpeechLanguage = "";

function normalizedSettings(state = {}) { return { textScale: Number(state.textScale ?? 100), lineSpacing: Number(state.lineSpacing ?? 1.5), readingWidth: Number(state.readingWidth ?? 70), contrast: Boolean(state.contrast), focus: Boolean(state.focus) }; }
function apply(state) { const next = normalizedSettings(state); root.style.setProperty("--up-text-scale", `${next.textScale / 100}`); root.style.setProperty("--up-line-spacing", String(next.lineSpacing)); root.style.setProperty("--up-reading-width", `${next.readingWidth}ch`); root.dataset.upContrast = String(next.contrast); root.dataset.upFocus = String(next.focus); }
function voiceForLanguage(language) { if (!language || !window.speechSynthesis?.getVoices) return null; const voices = window.speechSynthesis.getVoices(); const requested = language.toLowerCase(); return voices.find(voice => voice.lang?.toLowerCase() === requested) || voices.find(voice => voice.lang?.toLowerCase().split("-")[0] === requested.split("-")[0]) || null; }
function readAloud(text, language, sendResponse) { if (!text) { sendResponse?.({ applied: false, error: "No readable text was found." }); return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); const selectedLanguage = typeof language === "string" ? language : ""; const voice = voiceForLanguage(selectedLanguage); if (selectedLanguage) utterance.lang = selectedLanguage; if (voice) utterance.voice = voice; window.speechSynthesis.speak(utterance); sendResponse?.({ applied: true, language: selectedLanguage || undefined, voiceLanguage: voice?.lang, usedFallbackVoice: Boolean(selectedLanguage && !voice) }); }
function isUnderProgressWebsite() { const host = window.location.hostname; return host === "under-progress-psi.vercel.app" || /^under-progress(?:-[a-z0-9-]+)?\.vercel\.app$/.test(host); }
function sendProfileToWebsite(settings) { if (!isUnderProgressWebsite() || !settings) return; window.postMessage({ source: "under-progress-extension", type: "extension-profile", settings: normalizedSettings(settings), profile: savedProfile }, window.location.origin); }

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { if (!message) return; if (message.type === "ping") { sendResponse?.({ ready: true }); return; } if (message.type === "apply") { apply(message.state); sendResponse?.({ applied: true }); return; } if (message.type === "speak") { const selected = window.getSelection()?.toString().trim(); const fallback = document.querySelector("main, article, [role=main]")?.innerText?.slice(0, 1800) || document.body.innerText.slice(0, 1800); const text = selected || fallback; chrome.storage.sync.get(["underProgressProfile", "underProgressSpeechLanguage"], ({ underProgressProfile, underProgressSpeechLanguage }) => { savedProfile = underProgressProfile || savedProfile; preferredSpeechLanguage = underProgressSpeechLanguage || savedProfile?.language || preferredSpeechLanguage; readAloud(text, preferredSpeechLanguage, sendResponse); }); return true; } if (message.type === "pause-speech") { if (window.speechSynthesis.speaking && !window.speechSynthesis.paused) { window.speechSynthesis.pause(); sendResponse?.({ applied: true }); } else sendResponse?.({ applied: false, error: "There is no active reading to pause." }); return; } if (message.type === "resume-speech") { if (window.speechSynthesis.paused) { window.speechSynthesis.resume(); sendResponse?.({ applied: true }); } else sendResponse?.({ applied: false, error: "There is no paused reading to resume." }); } });
chrome.storage.sync.get(["underProgress", "underProgressProfile", "underProgressSpeechLanguage"], ({ underProgress, underProgressProfile, underProgressSpeechLanguage }) => { savedProfile = underProgressProfile || null; preferredSpeechLanguage = underProgressSpeechLanguage || savedProfile?.language || ""; if (underProgress && !isUnderProgressWebsite()) apply(underProgress); if (isUnderProgressWebsite()) { window.postMessage({ source: "under-progress-extension", type: "connection-status" }, window.location.origin); sendProfileToWebsite(underProgress); } });
chrome.storage.onChanged.addListener((changes, areaName) => { if (areaName !== "sync") return; if (changes.underProgressProfile) savedProfile = changes.underProgressProfile.newValue || null; if (changes.underProgressSpeechLanguage) preferredSpeechLanguage = changes.underProgressSpeechLanguage.newValue || savedProfile?.language || ""; if (changes.underProgress) { const settings = normalizedSettings(changes.underProgress.newValue); if (!isUnderProgressWebsite()) apply(settings); sendProfileToWebsite(settings); } });
window.addEventListener("message", (event) => { if (!isUnderProgressWebsite() || event.origin !== window.location.origin || event.source !== window) return; const message = event.data; if (!message || message.source !== "under-progress-website") return; if (message.type === "request-profile") { chrome.storage.sync.get(["underProgress", "underProgressProfile", "underProgressSpeechLanguage"], ({ underProgress, underProgressProfile, underProgressSpeechLanguage }) => { savedProfile = underProgressProfile || null; preferredSpeechLanguage = underProgressSpeechLanguage || savedProfile?.language || ""; window.postMessage({ source: "under-progress-extension", type: "connection-status" }, window.location.origin); sendProfileToWebsite(underProgress); }); } if (message.type === "set-language" && typeof message.language === "string") { chrome.storage.sync.get(["underProgressProfile"], ({ underProgressProfile }) => { preferredSpeechLanguage = message.language; savedProfile = { ...(underProgressProfile || {}), language: message.language }; chrome.storage.sync.set({ underProgressProfile: savedProfile, underProgressSpeechLanguage: message.language }, () => window.postMessage({ source: "under-progress-extension", type: "language-saved", language: message.language }, window.location.origin)); }); } if (message.type === "save-profile" && message.settings) { const settings = normalizedSettings(message.settings); savedProfile = { ...(savedProfile || {}), ...(message.profile || {}) }; preferredSpeechLanguage = savedProfile.language || preferredSpeechLanguage; const preset = { id: "website-default", name: savedProfile?.presetName || "Website default", settings }; chrome.storage.sync.get(["underProgressPresets"], ({ underProgressPresets }) => { const previous = Array.isArray(underProgressPresets) ? underProgressPresets.filter(item => item?.id !== "website-default") : []; chrome.storage.sync.set({ underProgress: settings, underProgressProfile: savedProfile, underProgressSpeechLanguage: preferredSpeechLanguage, underProgressPresets: [...previous, preset], underProgressDefaultPreset: "website-default" }, () => { window.postMessage({ source: "under-progress-extension", type: "preset-saved", presetName: preset.name }, window.location.origin); }); }); } });
